export const SUBJECTS = [
    "Mathematics",
    "English",
    "Science",
    "Social Studies",
    "Environmental Studies",
    "Physical Education",
    "Art",
    "Music",
    "Computer Science",
    "History",
    "Geography",
    "Biology",
    "Chemistry",
    "Physics",
    "Economics",
    "Political Science",
    "Sociology",
    "Psychology",
    "Philosophy",
    "Business Studies",
    "Accountancy",
    "Statistics",
    "Computer Applications",
    "Information Technology",
    "Electronics",
    "Mechanical Engineering",
    "Civil Engineering",
    "Electrical Engineering",
    "Marketing",
    "Finance",
    "Human Resource Management",
    "Operations Management",
    "Entrepreneurship",
    "Public Administration",
    "Law",
    "Education",
    "Library Science",
    "Biotechnology",
    "Genetics",
    "Microbiology",
    "Zoology",
    "Botany",
    "Environmental Science",
    "Agricultural Science",
    "Forestry",
    "Veterinary Science",
    "Medicine",
    "Dentistry",
    "Nursing",
    "Pharmacy",
    "Public Health",
    "Nutrition",
    "Physiotherapy",
    "Sports Science",
    "Astronomy",
    "Anthropology",
    "Archaeology",
    "Linguistics",
    "Literature",
    "Fine Arts",
    "Theatre",
    "Film Studies",
    "Media Studies",
    "Journalism",
    "Mass Communication",
    "International Relations",
    "Gender Studies",
    "Cultural Studies",
    "Theology",
    "Religious Studies",
    "Architecture",
    "Urban Planning",
    "Fashion Design",
    "Interior Design",
    "Graphic Design",
    "Animation",
    "Data Science",
    "Machine Learning",
    "Artificial Intelligence",
    "Cybersecurity",
    "Blockchain",
    "Robotics",
    "Software Engineering",
    "Network Engineering",
    "Game Development",
    "Digital Marketing",
    "Econometrics",
    "Geology",
    "Oceanography",
    "Meteorology",
    "Astrophysics",
    "Quantum Physics",
    "Neuroscience",
    "Bioinformatics",
    "Ecology",
    "Molecular Biology",
    "Social Work",
    "Cognitive Science",
    "Ethics",
    "Critical Thinking"
]


export const SUBJECTS_CHAPTERS = {
    "mathematics": ["Algebra", "Geometry", "Calculus"],
    "english": ["Grammar", "Literature", "Writing Skills"],
    "science": ["Matter", "Energy", "The Universe"],
    "social studies": ["Civics", "History", "Geography"],
    "environmental studies": ["Ecology", "Conservation", "Pollution"],
    "physical education": ["Fitness", "Sports Rules", "Nutrition"],
    "art": ["Drawing", "Painting", "Sculpture"],
    "music": ["Notes", "Instruments", "Genres"],
    "computer science": ["Programming Basics", "Data Structures", "Algorithms"],
    "history": ["Ancient Civilizations", "World Wars", "Modern History"],
    "geography": ["Physical Features", "Climate", "Human Geography"],
    "biology": ["Cell Biology", "Genetics", "Evolution"],
    "chemistry": ["Elements", "Chemical Reactions", "Organic Chemistry"],
    "physics": ["Mechanics", "Electromagnetism", "Quantum Physics"],
    "economics": ["Microeconomics", "Macroeconomics", "Global Trade"],
    "political science": ["Governance", "Political Systems", "Policy Analysis"],
    "sociology": ["Social Structures", "Culture", "Social Change"],
    "psychology": ["Human Behavior", "Cognitive Development", "Mental Health"],
    "philosophy": ["Ethics", "Metaphysics", "Logic"],
    "business studies": ["Management", "Marketing", "Entrepreneurship"],
    "accountancy": ["Financial Accounting", "Cost Accounting", "Auditing"],
    "statistics": ["Probability", "Descriptive Statistics", "Inferential Statistics"],
    "computer applications": ["Office Applications", "Internet Basics", "Database Management"],
    "information technology": ["Networking", "Cloud Computing", "Cybersecurity"],
    "electronics": ["Circuits", "Semiconductors", "Communication Systems"],
    "mechanical engineering": ["Thermodynamics", "Fluid Mechanics", "Materials Science"],
    "civil engineering": ["Structural Analysis", "Transportation Engineering", "Surveying"],
    "electrical engineering": ["Circuits and Systems", "Power Systems", "Control Systems"],
    "marketing": ["Market Research", "Branding", "Digital Marketing"],
    "finance": ["Financial Planning", "Investment Strategies", "Corporate Finance"],
    "human resource management": ["Recruitment", "Training and Development", "Organizational Behavior"],
    "operations management": ["Process Design", "Supply Chain Management", "Quality Control"],
    "entrepreneurship": ["Ideation", "Business Planning", "Scaling Strategies"],
    "public administration": ["Public Policy", "Bureaucracy", "Governance"],
    "law": ["Constitutional Law", "Criminal Law", "Corporate Law"],
    "education": ["Teaching Strategies", "Curriculum Development", "Assessment"],
    "library science": ["Cataloging", "Information Retrieval", "Digital Libraries"],
    "biotechnology": ["Genetic Engineering", "Bioprocessing", "Bioinformatics"],
    "genetics": ["DNA Structure", "Heredity", "Genetic Disorders"],
    "microbiology": ["Microbial Structure", "Pathogenesis", "Virology"],
    "zoology": ["Animal Physiology", "Ecology", "Evolution"],
    "botany": ["Plant Anatomy", "Photosynthesis", "Plant Reproduction"],
    "environmental science": ["Ecosystems", "Climate Change", "Sustainability"],
    "agricultural science": ["Soil Science", "Crop Production", "Agroecology"],
    "forestry": ["Silviculture", "Forest Management", "Wildlife Conservation"],
    "veterinary science": ["Animal Anatomy", "Disease Management", "Surgery"],
    "medicine": ["Human Anatomy", "Pharmacology", "Pathology"],
    "dentistry": ["Oral Anatomy", "Dental Materials", "Clinical Dentistry"],
    "nursing": ["Patient Care", "Anatomy", "Clinical Procedures"],
    "pharmacy": ["Medicinal Chemistry", "Pharmacokinetics", "Drug Formulation"],
    "public health": ["Epidemiology", "Health Policies", "Community Health"],
    "nutrition": ["Macronutrients", "Vitamins and Minerals", "Diet Planning"],
    "physiotherapy": ["Anatomy", "Rehabilitation", "Exercise Therapy"],
    "sports science": ["Biomechanics", "Sports Nutrition", "Sports Psychology"],
    "astronomy": ["The Solar System", "Stars and Galaxies", "Cosmology"],
    "anthropology": ["Human Evolution", "Cultural Anthropology", "Archaeology"],
    "archaeology": ["Excavation Techniques", "Ancient Civilizations", "Artifacts"],
    "linguistics": ["Phonetics", "Syntax", "Sociolinguistics"],
    "literature": ["Poetry", "Drama", "Prose"],
    "fine arts": ["Art History", "Painting Techniques", "Sculpture"],
    "theatre": ["Acting", "Scriptwriting", "Directing"],
    "film studies": ["Film History", "Cinematography", "Film Analysis"],
    "media studies": ["Media Theories", "Digital Media", "Advertising"],
    "journalism": ["Reporting", "Editing", "Ethics in Journalism"],
    "mass communication": ["Communication Models", "Public Relations", "Broadcasting"],
    "international relations": ["Diplomacy", "Global Organizations", "Geopolitics"],
    "gender studies": ["Feminist Theory", "Gender Roles", "Intersectionality"],
    "cultural studies": ["Cultural Theory", "Media Culture", "Identity"],
    "theology": ["Religious Texts", "Ethics", "Comparative Religion"],
    "religious studies": ["World Religions", "Rituals", "Belief Systems"],
    "architecture": ["Building Design", "Architectural History", "Urban Planning"],
    "urban planning": ["Zoning", "Transportation Planning", "Sustainable Development"],
    "fashion design": ["Textiles", "Garment Construction", "Fashion Trends"],
    "interior design": ["Space Planning", "Lighting", "Furniture Design"],
    "graphic design": ["Typography", "Branding", "Digital Illustration"],
    "animation": ["2D Animation", "3D Animation", "Motion Graphics"],
    "data science": ["Data Analysis", "Machine Learning", "Big Data"],
    "machine learning": ["Supervised Learning", "Neural Networks", "Natural Language Processing"],
    "artificial intelligence": ["AI Basics", "Machine Learning", "Robotics"],
    "cybersecurity": ["Network Security", "Cryptography", "Ethical Hacking"],
    "blockchain": ["Blockchain Basics", "Smart Contracts", "Cryptocurrency"],
    "robotics": ["Robotics Basics", "Sensors", "AI Integration"],
    "software engineering": ["SDLC", "Agile Methodologies", "Software Testing"],
    "network engineering": ["Network Architecture", "Protocols", "Network Security"],
    "game development": ["Game Design", "Game Engines", "Game AI"],
    "digital marketing": ["SEO", "Social Media Marketing", "Analytics"],
    "econometrics": ["Regression Analysis", "Time Series Analysis", "Econometric Models"],
    "geology": ["Rocks and Minerals", "Plate Tectonics", "Earthquakes"],
    "oceanography": ["Ocean Currents", "Marine Life", "Climate Impact"],
    "meteorology": ["Weather Patterns", "Climate Change", "Forecasting"],
    "astrophysics": ["Stellar Physics", "Galaxies", "Dark Matter"],
    "quantum physics": ["Quantum Mechanics", "Quantum Fields", "Applications"],
    "neuroscience": ["Brain Structure", "Neurotransmitters", "Neural Pathways"],
    "bioinformatics": ["Genomic Data", "Sequence Alignment", "Protein Structure"],
    "ecology": ["Ecosystems", "Biodiversity", "Conservation"],
    "molecular biology": ["DNA", "RNA", "Proteins"],
    "social work": ["Community Work", "Social Policies", "Mental Health Support"],
    "cognitive science": ["Perception", "Memory", "Decision Making"],
    "ethics": ["Moral Philosophy", "Ethical Dilemmas", "Contemporary Ethics"],
    "critical thinking": ["Logical Reasoning", "Argument Analysis", "Problem Solving"]
  }
  